### PR TITLE
Add support for creating and retrieving posts

### PR DESCRIPTION
**Pull request by juannyG**
### Summary
* A post is created with the contents of the post and a signature of the post via the user's wallet
* Add a `Post` structure which holds
  * The address of the creator
  * The contents of the post
  * The signature of the post, which is considered to be the ID of the post
* The contract stores a mapping of post signatures to Post structures
  * `postStore`
* The contract stores an array of post signatures in a community (there's only one community, for now)
  * `communityPostIDs`
* The user profile stores a list of all of the user's post signatures
* A registered user can retrieve a specific post via a post signature
* A registered user can retrieve all posts of another registered user
* A registered user can retrieve all posts in a community

### Extras
* Add support for passing CLI arguments to `forge test` in our CLI wrapper
* NOTE/TODO items peppered throughout the contract where I wanted to start with a concept, but keep it basic/simple for the MVP
* Move events into their own `sol` file
  * Useful for resuse in tests
* Separate post & user mgmt tests

### CODE REVIEW

**Comment by juannyG** [comment]
Diagram of how the new post related data structures



post-datastructures

**Comment by juannyG** [comment]
To view the comparison BEFORE the formatting commit, you can use: https://github.com/juannyG/coms6998/compare/8444de3f69d9aedfd332f76cca55f6c68b72cc39...de995d7c376fb9c62ab7dd38971a1769e25ba061, where `8444de3f69d9aedfd332f76cca55f6c68b72cc39` is the current commit of `dev`

**Comment by hungchingliu** [comment]
Not sure if I miss something from the previous meeting. I'm wondering why we need to signed the content. Is it to make it verifiable? I think the whole transaction will already be signed and the content is also included in the call data of the transaction so it's already verifiable that the content is coming from the address owner.

**Review by hungchingliu — COMMENTED** [review]
Not sure if I miss something from the previous meeting. I'm wondering why we need to signed the content of the post. Is it to make it verifiable? I think the whole transaction will already be signed and the content is also included in the call data of the transaction so it's already verifiable that the content is coming from the address owner.

**Comment by juannyG** [comment]
> Not sure if I miss something from the previous meeting. I'm wondering why we need to signed the content of the post. Is it to make it verifiable? I think the whole transaction will already be signed and the content is also included in the call data of the transaction so it's already verifiable that the content is coming from the address owner.

Great question! Your 100% correct about the transaction. However, as I was developing this API, here are some of the things I was thinking about:
1. `getPost` - how do I retrieve a single post? What is the ID of a post? I can't use the txID, because it doesn't exist yet until AFTER the "create post" tx completes. We can't use the block number, as [solidity provides minimal guarantees about available block # information when a contract is processing a request](https://docs.soliditylang.org/en/v0.8.28/units-and-global-variables.html#block-and-transaction-properties). Maybe it's just the index in an array in the contract, however...
2. When we move content off-chain and even more so, into something like mongoDB - the signature of the content provides the guarantee that no tampering has occurred since the content was posted. If we store it in a centralized web2 data store without a signature, there's no way to verify the data is in fact. 
3. When we want to transfer ownership of a post or an entire account - instead of relying on a potentially long history of tx receipts (emitted events), the state of the signatures can be updated on chain - i.e. you allow your post to be transferred to me - I can then claim ownership by resigning the content with my wallet.

It felt to me that we get a bit more freedom by decoupling the tx signature from the content signature.

**Review by Yixli9811 — APPROVED** [review]

**Pull request merged**
